### ISSUE TITLE
Enemies clipping through ship on Devastation

### ISSUE THREAD

**Issue by Mudkipster** [GenericGMD/Generic-Moons#2]
What it says in the title. Enemies can clip through the ship walls on Devastation. I assume this is the same for all of the moons as I saw someone complain about it for Icebound.

**Comment by GenericGMD** [comment]
this might either be an issue with lethal expansion itself, or a problem with the navmesh ive been using. I'm looking into it but no guarantee that it can be fixed.

**Comment by GenericGMD** [comment]
havent logged into github in a while, this has been fixed.
