### ISSUE TITLE
Crash when going to any of the modded moons

### ISSUE THREAD

**Issue by agreedSkiing** [GenericGMD/Generic-Moons#4]
Using LethalExpansion v1.3.36 by HolographicWings and BepInExPack v5.4.2100 by BepInEx only. All my other mods are disabled

## Icebound
![image](https://github.com/GenericGMD/Generic-Moons/assets/93997033/51f87a95-90fd-42a2-a7b1-ba9a168a183d)

## Hydro
![image](https://github.com/GenericGMD/Generic-Moons/assets/93997033/dd977603-7028-45f6-a8db-b533067107a6)

## Vertigo
![image](https://github.com/GenericGMD/Generic-Moons/assets/93997033/cdbd8615-ebb9-4b9d-aa98-3bd959fa3bf8)

## Devastation
![image](https://github.com/GenericGMD/Generic-Moons/assets/93997033/3381a355-e690-46f3-bb5b-3109c39f3c00)

**Comment by GenericGMD** [comment]
Thanks for reporting. I just asked a few of my friends to test themselves and I will when I get home in a few hours. If we figure anything out I’ll let you know.

**Comment by GenericGMD** [comment]
So you literally don’t have anything else? Just those two? If you have more can you send a picture of your modlist because some really weird stuff breaks certain things.

**Comment by agreedSkiing** [comment]
Here is the profile as a code :)
018d8f46-2c7f-e2f2-fcdf-8da41d3d5cce

**Comment by agreedSkiing** [comment]
And just created a new profile that only has the needed dependencies installed 018d8f4a-5990-3c99-7ec9-a2f3ec34c8f7 
![image](https://github.com/GenericGMD/Generic-Moons/assets/93997033/8fd37ecd-eafc-4424-afdd-60f5f972b017)
And i don't know if it matters but I'm running this with Proton on a Linux machine

**Comment by agreedSkiing** [comment]
@GenericGMD the mod now works after lethalexpansion updated to v 1.3.37
