### ISSUE TITLE
Generic interiors Bug Report

### ISSUE THREAD

**Issue by VanilaBOI** [GenericGMD/Generic-Moons#6]
First of, I have to say this interior SLAPS. Love the posters and the vanilla feel.

I have noticed tough that centipedes can't seem to fine a place to hide and just end up roaming the entire time.

Also through Imperium I found a spot for loot to spawn in the wall(I think it's a part of the ramp tile)
![20241022013613_1](https://github.com/user-attachments/assets/53e1f9b9-8b3c-4d0e-b3dc-bf3ed02030d8)
![20241022013619_1](https://github.com/user-attachments/assets/347bd758-5fe7-4fc7-8019-f42198898bb8)

And just as a side note, I get if it's intentional but the whole place is too lit up for me.
I think it be better if the amount of lights that are on/off could be closer to the other interiors.

**Comment by GenericGMD** [comment]
A small bit of navmesh might be stuck in the wall. looking into it.

**Comment by GenericGMD** [comment]
for centipedes though, no idea. they work 50% of the time its kinda like a diceroll. wesleys interiors seem to have this issue too.

**Comment by GenericGMD** [comment]
that was exactly it. should be fixed now. patch going up soon.

**Comment by GenericGMD** [comment]
patch is up
